export default {
  login: 'heangly',
  id: 45981788,
  node_id: 'MDQ6VXNlcjQ1OTgxNzg4',
  avatar_url: 'https://avatars.githubusercontent.com/u/45981788?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/heangly',
  html_url: 'https://github.com/heangly',
  followers_url: 'https://api.github.com/users/heangly/followers',
  following_url: 'https://api.github.com/users/heangly/following{/other_user}',
  gists_url: 'https://api.github.com/users/heangly/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/heangly/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/heangly/subscriptions',
  organizations_url: 'https://api.github.com/users/heangly/orgs',
  repos_url: 'https://api.github.com/users/heangly/repos',
  events_url: 'https://api.github.com/users/heangly/events{/privacy}',
  received_events_url: 'https://api.github.com/users/heangly/received_events',
  type: 'User',
  site_admin: false,
  name: 'Heang Ly',
  company: null,
  blog: 'https://heangly.netlify.app/',
  location: 'Bensalem, PA',
  email: null,
  hireable: true,
  bio:
    'Hi! I am Heang Ly. Currently, I am a senior majoring in Computer Science at Drexel University.',
  twitter_username: null,
  public_repos: 17,
  public_gists: 0,
  followers: 1,
  following: 3,
  created_at: '2018-12-18T22:36:51Z',
  updated_at: '2021-01-16T12:44:49Z',

  // login: 'john-smilga',
  // id: 42133389,
  // node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  // avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  // gravatar_id: '',
  // url: 'https://api.github.com/users/john-smilga',
  // html_url: 'https://github.com/john-smilga',
  // followers_url: 'https://api.github.com/users/john-smilga/followers',
  // following_url:
  //   'https://api.github.com/users/john-smilga/following{/other_user}',
  // gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  // starred_url:
  //   'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  // subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  // organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  // repos_url: 'https://api.github.com/users/john-smilga/repos',
  // events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  // received_events_url:
  //   'https://api.github.com/users/john-smilga/received_events',
  // type: 'User',
  // site_admin: false,
  // name: 'John Smilga',
  // company: 'Coding Addict',
  // blog: 'www.johnsmilga.com',
  // location: 'Los Angeles',
  // email: null,
  // hireable: null,
  // bio: 'Creator of Coding Addict',
  // twitter_username: 'john_smilga',
  // public_repos: 152,
  // public_gists: 0,
  // followers: 1495,
  // following: 0,
  // created_at: '2018-08-06T06:48:23Z',
  // updated_at: '2020-07-08T05:01:32Z',
};
